defaults:
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-last-modified-at
last-modified-at:
  date-format: "%d-%b-%y"
collections:
  characters:
    output: true
  concepts:
    output: true
  organizations:
    output: true
  rulesets:
    output: true
