backend:
  name: github
  repo: zuedev/paradise
media_folder: "assets/media"
publish_mode: editorial_workflow
site_url: https://paradise.zue.dev
display_url: https://paradise.zue.dev
# logo_url: https://your-site.com/images/logo.svg
collections:
  - label: "Characters"
    name: "characters"
    folder: "_characters"
    create: true
    fields:
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Thumbnail Placeholder",
          name: "thumbnailPlaceholder",
          widget: "boolean",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Concepts"
    name: "concepts"
    folder: "_concepts"
    create: true
    fields:
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Thumbnail Placeholder",
          name: "thumbnailPlaceholder",
          widget: "boolean",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Organizations"
    name: "organizations"
    folder: "_organizations"
    create: true
    fields:
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Thumbnail Placeholder",
          name: "thumbnailPlaceholder",
          widget: "boolean",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Rulesets"
    name: "rulesets"
    folder: "_rulesets"
    create: true
    fields:
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Thumbnail Placeholder",
          name: "thumbnailPlaceholder",
          widget: "boolean",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
